# Generated by Django 2.1.5 on 2019-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(default=1, help_text='The Bank Phone Number', max_length=10)),
                ('name', models.CharField(default=1, help_text='The Blood Bank Name', max_length=500)),
                ('location', models.CharField(help_text='The Bank location in word', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
