# Generated by Django 2.1.5 on 2019-02-16 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0003_auto_20190216_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(default=0, help_text='The Blood Group of the User', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(default=0, help_text='The Blood Group of the User', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=0, help_text='The Location of the User', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, help_text='The Name of the User', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=0, help_text='The state of the User', max_length=500),
        ),
        migrations.RenameModel(
            old_name='Bank',
            new_name='Blood_Bank',
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.User'),
        ),
        migrations.AddField(
            model_name='blood_unit',
            name='blood_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.Blood_Bank'),
        ),
    ]
