# Generated by Django 2.1.5 on 2019-02-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0004_auto_20190216_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, help_text='The Name of the User', max_length=500)),
                ('location', models.CharField(default=0, help_text='The Location of the User', max_length=500)),
                ('state', models.CharField(default=0, help_text='The state of the User', max_length=500)),
                ('image', models.CharField(default=0, help_text='The image of the campaign', max_length=2000)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.Blood_Bank')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fcm',
            field=models.CharField(default=0, help_text='The FCM Registration Token for the user', max_length=1000),
        ),
    ]
