# Generated by Django 2.1.5 on 2019-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0006_auto_20190216_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_bank',
            name='state',
            field=models.CharField(default=0, help_text='The state of the User', max_length=500),
        ),
    ]
