# Generated by Django 2.1.5 on 2019-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0007_blood_bank_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_bank',
            name='image',
            field=models.CharField(default=0, help_text='The image of the campaign', max_length=2000),
        ),
    ]
