# Generated by Django 2.1.5 on 2019-02-16 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0009_auto_20190216_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
