# Generated by Django 2.1.5 on 2019-02-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0010_campaign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='image',
            field=models.CharField(default='https://excelcityindia.com/oc-content/uploads/40/4927.png', help_text='The image of the campaign', max_length=2000),
        ),
        migrations.AlterField(
            model_name='blood_unit',
            name='blood_group',
            field=models.CharField(default=0, help_text='The Blood Group of the User', max_length=10),
        ),
    ]
