# Generated by Django 2.1.5 on 2019-02-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0011_auto_20190217_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.CharField(default='https://excelcityindia.com/oc-content/uploads/40/4927.png', help_text='The image of the campaign', max_length=2000),
        ),
    ]
