# Generated by Django 2.1.5 on 2019-02-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=1, max_length=5000)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=1, max_length=3000)),
                ('cheers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_feed.Ranger'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_feed.Ask'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_feed.Ranger'),
        ),
    ]
