# Generated by Django 2.1.5 on 2019-02-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='ranger',
        ),
        migrations.RenameField(
            model_name='ask',
            old_name='author',
            new_name='ranger',
        ),
    ]
